language:
- python
python:
- '3.4'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key: 00a94497-1111-1111-0000-193456789c5
  app: shielded-shore-19702
  on:
    branch: master
    python: '3.4'
    repo: ipeacocks/flasktaskr
