# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: one-level.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fone-level.proto\"6\n\x04\x43ity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03zip\x18\x02 \x01(\x05\x12\x13\n\x0b\x63ountryName\x18\x03 \x01(\t\"+\n\x06Street\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x04\x63ity\x18\x02 \x01(\x0b\x32\x05.City\"A\n\x08\x42uilding\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\t\x12\x17\n\x06street\x18\x03 \x01(\x0b\x32\x07.Streetb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'one_level_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CITY._serialized_start=19
  _CITY._serialized_end=73
  _STREET._serialized_start=75
  _STREET._serialized_end=118
  _BUILDING._serialized_start=120
  _BUILDING._serialized_end=185
# @@protoc_insertion_point(module_scope)
