"""empty message

Revision ID: 3b16b9878563
Revises: 35c7ccb923be
Create Date: 2015-06-05 00:44:06.792487

"""

# revision identifiers, used by Alembic.
revision = '3b16b9878563'
down_revision = '35c7ccb923be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
